generate_disbursements_worker:
  cron: "0 3 * * *"
  class: "Crons::GenerateMerchantsDisbursementsWorker"
  args:
    schedule_indication: "Every day at 3 am, generate disbursements for all merchant"

generate_merchant_fees_charges_worker:
  cron: "0 0 1 * *"
  class: "Crons::GenerateMerchantsFeesChargesWorker"
  args:
    schedule_indication: "Every first day of the month at 0 am, generate merchants fees charges"